### PR TITLE
Danish typo

### PR DESCRIPTION
**Pull request by Alkarex**
Found by one of our readers

### CODE REVIEW

**Comment by Alkarex** [comment]
Ping :-)
P.S. Also used for https://github.com/morevnaproject/subtitles-translation/pull/30

**Comment by Alkarex** [comment]
Petit rappel @Deevad

**Comment by Deevad** [comment]
Hey @Alkarex ; I don't know how I missed the PR notification for so long on this one ; I'll merge all your work (thank you!) The renderfarm was in refactor all last week, and same for a big maintenance over all the 5800 SVGs. It was epic!

**Comment by Alkarex** [comment]
Great :-)

**Pull request merged**
