### PR TITLE
[it] Little typo

### PR DESCRIPTION
**Pull request by cgand**
Little typo on Coriander name

### CODE REVIEW

**Comment by Deevad** [comment]
In french it's also "Fin" so I didn't had an issue with it ; and knew it could be used in english as well ( like @agryson said ). But, I can imagine 'End' to be easier to understand, and I understand the pull request of @cgand .
All in all, I trust @agryson about the general feel of english version ; and I empower him to have the last word on this topic.

**Comment by Deevad** [comment]
Merged both , I'll revert the FIN > END one :)

**Comment by agryson** [comment]
Well, I think that we should keep "FIN" but also that @cgand makes a good point about understandability, so we should maybe keep this ticket open for other people with the same problem. 
If they feel 'FIN' is confusing, they should comment here and we can always reconsider at a later time.

**Comment by Deevad** [comment]
Thank you @agryson , that's wise. Let see.

**Pull request merged**
